name: CI/CD for my FYP

on:
    push:
        branches:
            - main
env:
    BUILD_NUMBER: ${{github.run_number}}

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout the repositories
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: setup node
              uses: actions/setup-node@v3
              with:
                node-versio: 24

            - name: install frotend dependencies
              working-directory: ./frontend
              run: npm install 

            - name: install backend dependencies
              working-directory: ./backend
              run: npm install 

              # Trivy check the repo for vulnerabilities
            - name: scanning repo
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: repo
                security-checks: secrets
                exit-code: 0

              # build and scan frontend docker image
            - name: build frontend docker image
              run: |
                docker build \
                  --build-arg VITE_BACKEND_URI="http://${{ secrets.EC2_IP }}:8000" \
                  --build-arg VITE_SOCKET_URI="http://${{ secrets.EC2_IP }}:8000" \
                  -t muzaffaribrar/fyp-frontend:$BUILD_NUMBER \
                  -t muzaffaribrar/fyp-frontend:latest \
                  ./frontend
            
            #run: docker build -t muzaffaribrar/fyp-frontend:$BUILD_NUMBER -t muzaffaribrar/fyp-frontend:latest ./frontend

            - name: scanning frontend image 
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: image
                image-ref: muzaffaribrar/fyp-frontend:${{ env.BUILD_NUMBER }}
                security-checks: secrets
                exit-code: 0
                
            # push to docker hub
            - name: Push frontend image to docker hub
              env:
                DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
                DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
              run: |
                echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
                docker push muzaffaribrar/fyp-frontend:$BUILD_NUMBER
                docker push muzaffaribrar/fyp-frontend:latest

            # build and scanning backend image
            - name: build backend image
              run: docker build -t muzaffaribrar/fyp-backend:$BUILD_NUMBER -t muzaffaribrar/fyp-backend:latest ./backend

            - name: scanning image by trivy
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: image
                image-ref: muzaffaribrar/fyp-backend:${{ env.BUILD_NUMBER }}
                security-checks: secrets
                exit-code: 0

            # push image to docker hub
            - name: push backend image to docker hub
              env:
                DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
                DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
              run: |
                echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                docker push muzaffaribrar/fyp-backend:$BUILD_NUMBER
                docker push muzaffaribrar/fyp-backend:latest

            # Pull and Deploy on EC2
            - name: Pull images from docker hub and deploy on ec2
              env:
                env:
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                VITE_BACKEND_URI: "http://${{secrets.EC2_IP}}:8000"
                VITE_SOCKET_URI: "http://${{secrets.EC2_IP}}:8000"
                MONGO_URI: ${{secrets.MONGO_URI}}
                ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
                REFRESH_TOKEN: ${{secrets.REFRESH_TOKEN}}
                CLOUDINARY_NAME: ${{secrets.CLOUDINARY_NAME}}
                CLOUDINARY_KEY: ${{secrets.CLOUDINARY_KEY}}
                CLOUDINARY_SECRET: ${{secrets.CLOUDINARY_SECRET}}
                SMTP_USER: ${{secrets.SMTP_USER}}
                SMTP_PASS: ${{secrets.SMTP_PASS}}
                FRONTEND_URL: "http://${{secrets.EC2_IP}}:5173"
                EC2_IP: ${{secrets.EC2_IP}}
              run: |
                echo "${{secrets.KEY_PEM}}" > key.pem
                chmod 600 key.pem
                

                # ssh and copy docker compose to ec2 
                scp -o StrictHostKeyChecking=no -i key.pem ./docker-compose.yml ubuntu@"$EC2_IP":/home/ubuntu/FYP/docker-compose.yml

                # ssh -o StrictHostKeychecking=no -i key.pem ubuntu@"$EC2_IP" << EOF

                # # inside the FYP/frontend place env
                # cd /home/ubuntu/FYP
                # mkdir frontend

                # cat <<EOF > frontend/.env
                # VITE_BACKEND_URI=${VITE_BACKEND_URI}
                # VITE_SOCKET_URI=${VITE_SOCKET_URI}
                # EOF
                # chmod 600 frontend/.env

                # EOF

                # ssh -o StrictHostKeychecking=no -i key.pem ubuntu@"$EC2_IP" << EOF

                # # inside the FYP/backend place env
                # cd /home/ubuntu/FYP
                # mkdir backend

                # cat <<EOF > backend/.env
                # PORT=8000
                # MONGO_URI=${MONGO_URI}
                # ACCESS_TOKEN=${ACCESS_TOKEN}
                # ACCESS_TOKEN_EXPIRY=5h
                # REFRESH_TOKEN=${REFRESH_TOKEN}
                # REFRESH_TOKEN_EXPIRY=12h
                # CLOUDINARY_NAME=${CLOUDINARY_NAME}
                # CLOUDINARY_KEY=${CLOUDINARY_KEY}
                # CLOUDINARY_SECRET=${CLOUDINARY_SECRET}
                # SMTP_USER=${SMTP_USER}
                # SMTP_PASS=${SMTP_PASS}
                # FRONTEND_URL=${FRONTEND_URL}
                # EOF
                # chmod 600 backend/.env

                # EOF 

                # ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@"$EC2_IP" <<'ENDSSH'
                # cd /home/ubuntu/FYP
                # mkdir -p frontend
                # ENDSSH

                # ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@"$EC2_IP" <<EOF
                # cat > /home/ubuntu/FYP/frontend/.env <<EOT
                # VITE_BACKEND_URI=${VITE_BACKEND_URI}
                # VITE_SOCKET_URI=${VITE_SOCKET_URI}
                # EOT
                # chmod 600 /home/ubuntu/FYP/frontend/.env
                # EOF
                
                #CREATING BACKEND .ENV INSIDE /BACKEND
                ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@"$EC2_IP" <<'ENDSSH'
                cd /home/ubuntu/FYP
                mkdir -p backend
                ENDSSH

                ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@"$EC2_IP" <<EOF
                cat > /home/ubuntu/FYP/backend/.env <<EOT
                PORT=8000
                MONGO_URI=${MONGO_URI}
                ACCESS_TOKEN=${ACCESS_TOKEN}
                ACCESS_TOKEN_EXPIRY=5h
                REFRESH_TOKEN=${REFRESH_TOKEN}
                REFRESH_TOKEN_EXPIRY=12h
                CLOUDINARY_NAME=${CLOUDINARY_NAME}
                CLOUDINARY_KEY=${CLOUDINARY_KEY}
                CLOUDINARY_SECRET=${CLOUDINARY_SECRET}
                SMTP_USER=${SMTP_USER}
                SMTP_PASS=${SMTP_PASS}
                FRONTEND_URL=${FRONTEND_URL}
                EOT
                chmod 600 /home/ubuntu/FYP/backend/.env
                EOF


                #ssh into FYP
                ssh -o StrictHostKeychecking=no -i key.pem ubuntu@"$EC2_IP" << EOF

                # inside the FYP place env
                cd /home/ubuntu/FYP

                # login to docker hub so pull works
                echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

                # pull image and up the containers
                docker-compose pull
                docker-compose down
                docker-compose up -d
                
                EOF



